
kind: Service
metadata:
  name: brightbridge-service
spec:
  template:
    spec:
      containers:
        - name: hello-1
          image: us-docker.pkg.dev/cloudrun/container/hello
          env:
            - name: PORT
              value: "8080"
            - name: LOGGING_DESTINATION
              value: "CLOUD_LOGGING_ONLY"
          ports:
            - containerPort: 8080
